#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/ef882a4e6c6066007952de3bd7013f9940dc0de7/modules/openapi-generator/src/main/resources/php

set -e

WORKINGDIR="/app/php"

docker run --rm \
  -v "${PWD}/:/local" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/oas/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${PWD}/vendor"
bash "${PWD}/bin/php" composer install
printf "\n"

printf "Adding examples to /examples ...\n"
rm -f "${PWD}/examples/"*.php
cp -r "${PWD}/oas/examples/"*.php "${PWD}/examples/"

printf "Adding examples to Docs ...\n"
bash "${PWD}/bin/php" ./bin/generate-examples.php

printf "Running php-cs-fixer ...\n"
bash "${PWD}/bin/php" ./vendor/bin/php-cs-fixer fix --verbose

printf "Replacing strings ...\n"
docker run --rm \
  -v "${PWD}:${WORKINGDIR}" \
  -w "${WORKINGDIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${PWD}:${WORKINGDIR}" \
  -w "${WORKINGDIR}" \
  perl bash ./bin/scan_for

printf "Running unit tests ...\n"
bash "${PWD}/bin/php" ./vendor/bin/phpunit
printf "\n\n"

exit 1