<?php
require_once __DIR__ . '/vendor/autoload.php';

require_once 'library/HelloSign/AbstractList.php';
require_once 'library/HelloSign/AbstractObject.php';
require_once 'library/HelloSign/AbstractResource.php';
require_once 'library/HelloSign/AbstractResourceList.php';
require_once 'library/HelloSign/AbstractSignatureRequest.php';
require_once 'library/HelloSign/AbstractSignatureRequestWrapper.php';
require_once 'library/HelloSign/Account.php';
require_once 'library/HelloSign/BaseException.php';
require_once 'library/HelloSign/Client.php';
require_once 'library/HelloSign/EmbeddedResponse.php';
require_once 'library/HelloSign/EmbeddedSignatureRequest.php';
require_once 'library/HelloSign/Error.php';
require_once 'library/HelloSign/Event.php';
require_once 'library/HelloSign/FileResponse.php';
require_once 'library/HelloSign/OAuthToken.php';
require_once 'library/HelloSign/OAuthTokenRequest.php';
require_once 'library/HelloSign/Signature.php';
require_once 'library/HelloSign/SignatureList.php';
require_once 'library/HelloSign/SignatureRequest.php';
require_once 'library/HelloSign/SignatureRequestList.php';
require_once 'library/HelloSign/Signer.php';
require_once 'library/HelloSign/SignerList.php';
require_once 'library/HelloSign/Team.php';
require_once 'library/HelloSign/Template.php';
require_once 'library/HelloSign/TemplateList.php';
require_once 'library/HelloSign/TemplateSignatureRequest.php';
require_once 'library/HelloSign/UnclaimedDraft.php';
require_once 'library/HelloSign/Warning.php';
