#!/usr/bin/env bash

# see https://github.com/OpenAPITools/openapi-generator/tree/ef882a4e6c6066007952de3bd7013f9940dc0de7/modules/openapi-generator/src/main/resources/php

set -e

DIR=$(cd `dirname $0` && pwd)
WORKING_DIR="/app/php"

docker run --rm \
  -v "${DIR}/:/local" \
  -v "${DIR}/openapi-sdk.yaml:/local/openapi-sdk.yaml" \
  openapitools/openapi-generator-cli:v5.3.0 generate \
    -i "/local/openapi-sdk.yaml" \
    -c "/local/openapi-config.yaml" \
    -t "/local/templates" \
    -o "/local/"

printf "\nInstalling composer dependencies ...\n"
mkdir -p "${DIR}/vendor"
bash "${DIR}/bin/php" composer install
printf "\n"

printf "Adding examples to Docs ...\n"
bash "${DIR}/bin/php" ./bin/generate-examples.php

printf "Running php-cs-fixer ...\n"
bash "${DIR}/bin/php" ./vendor/bin/php-cs-fixer fix --verbose

printf "Replacing strings ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/replace

printf "Scanning for prohibited keywords ...\n"
docker run --rm \
  -v "${DIR}:${WORKING_DIR}" \
  -w "${WORKING_DIR}" \
  perl bash ./bin/scan_for

printf "Running unit tests ...\n"
bash "${DIR}/bin/php" ./vendor/bin/phpunit
printf "\n\n"

printf "Success!\n"
