<?php
/**
 * SubFormFieldsPerDocumentTypeEnum
 *
 * PHP version 7.3
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @see     https://openapi-generator.tech
 */

/**
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HelloSignSDK\Model;

/**
 * SubFormFieldsPerDocumentTypeEnum Class Doc Comment
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @see     https://openapi-generator.tech
 */
class SubFormFieldsPerDocumentTypeEnum
{
    /**
     * Possible values of this enum
     */
    public const CHECKBOX = 'checkbox';

    public const CHECKBOX_MERGE = 'checkbox-merge';

    public const DATE_SIGNED = 'date_signed';

    public const DROPDOWN = 'dropdown';

    public const HYPERLINK = 'hyperlink';

    public const INITIALS = 'initials';

    public const SIGNATURE = 'signature';

    public const RADIO = 'radio';

    public const TEXT = 'text';

    public const TEXT_MERGE = 'text-merge';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHECKBOX,
            self::CHECKBOX_MERGE,
            self::DATE_SIGNED,
            self::DROPDOWN,
            self::HYPERLINK,
            self::INITIALS,
            self::SIGNATURE,
            self::RADIO,
            self::TEXT,
            self::TEXT_MERGE,
        ];
    }
}
