<?php
/**
 * SubSigningOptions
 *
 * PHP version 7.3
 *
 * @category Class
 * @author   OpenAPI Generator team
 * @see     https://openapi-generator.tech
 */

/**
 * Dropbox Sign API
 *
 * Dropbox Sign v3 API
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: apisupport@hellosign.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace HelloSignSDK\Model;

use ArrayAccess;
use HelloSignSDK\ObjectSerializer;
use InvalidArgumentException;
use JsonSerializable;

/**
 * SubSigningOptions Class Doc Comment
 *
 * @category Class
 * @description This allows the requester to specify the types allowed for creating a signature.  **Note**: If &#x60;signing_options&#x60; are not defined in the request, the allowed types will default to those specified in the account settings.
 * @author   OpenAPI Generator team
 * @see     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class SubSigningOptions implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'SubSigningOptions';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'default_type' => 'string',
        'draw' => 'bool',
        'phone' => 'bool',
        'type' => 'bool',
        'upload' => 'bool',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'default_type' => null,
        'draw' => null,
        'phone' => null,
        'type' => null,
        'upload' => null,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'default_type' => 'default_type',
        'draw' => 'draw',
        'phone' => 'phone',
        'type' => 'type',
        'upload' => 'upload',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'default_type' => 'setDefaultType',
        'draw' => 'setDraw',
        'phone' => 'setPhone',
        'type' => 'setType',
        'upload' => 'setUpload',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'default_type' => 'getDefaultType',
        'draw' => 'getDraw',
        'phone' => 'getPhone',
        'type' => 'getType',
        'upload' => 'getUpload',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DEFAULT_TYPE_DRAW = 'draw';
    public const DEFAULT_TYPE_PHONE = 'phone';
    public const DEFAULT_TYPE_TYPE = 'type';
    public const DEFAULT_TYPE_UPLOAD = 'upload';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDefaultTypeAllowableValues()
    {
        return [
            self::DEFAULT_TYPE_DRAW,
            self::DEFAULT_TYPE_PHONE,
            self::DEFAULT_TYPE_TYPE,
            self::DEFAULT_TYPE_UPLOAD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param array|null $data Associated array of property values
     *                         initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['default_type'] = $data['default_type'] ?? null;
        $this->container['draw'] = $data['draw'] ?? false;
        $this->container['phone'] = $data['phone'] ?? false;
        $this->container['type'] = $data['type'] ?? false;
        $this->container['upload'] = $data['upload'] ?? false;
    }

    public static function fromArray(array $data): SubSigningOptions
    {
        /** @var SubSigningOptions $obj */
        $obj = ObjectSerializer::deserialize(
            $data,
            SubSigningOptions::class,
        );

        return $obj;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['default_type'] === null) {
            $invalidProperties[] = "'default_type' can't be null";
        }
        $allowedValues = $this->getDefaultTypeAllowableValues();
        if (!is_null($this->container['default_type']) && !in_array($this->container['default_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'default_type', must be one of '%s'",
                $this->container['default_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }

    /**
     * Gets default_type
     *
     * @return string
     */
    public function getDefaultType()
    {
        return $this->container['default_type'];
    }

    /**
     * Sets default_type
     *
     * @param string $default_type The default type shown (limited to the listed types)
     *
     * @return self
     */
    public function setDefaultType(string $default_type)
    {
        $allowedValues = $this->getDefaultTypeAllowableValues();
        if (!in_array($default_type, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'default_type', must be one of '%s'",
                    $default_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['default_type'] = $default_type;

        return $this;
    }

    /**
     * Gets draw
     *
     * @return bool|null
     */
    public function getDraw()
    {
        return $this->container['draw'];
    }

    /**
     * Sets draw
     *
     * @param bool|null $draw Allows drawing the signature
     *
     * @return self
     */
    public function setDraw(?bool $draw)
    {
        $this->container['draw'] = $draw;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return bool|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param bool|null $phone Allows using a smartphone to email the signature
     *
     * @return self
     */
    public function setPhone(?bool $phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets type
     *
     * @return bool|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param bool|null $type Allows typing the signature
     *
     * @return self
     */
    public function setType(?bool $type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets upload
     *
     * @return bool|null
     */
    public function getUpload()
    {
        return $this->container['upload'];
    }

    /**
     * Sets upload
     *
     * @param bool|null $upload Allows uploading the signature
     *
     * @return self
     */
    public function setUpload(?bool $upload)
    {
        $this->container['upload'] = $upload;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param mixed $offset Offset
     *
     * @return bool
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param mixed $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param mixed $offset Offset
     * @param mixed $value Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param mixed $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return scalar|object|array|null returns data which can be serialized by json_encode(), which is a value
     *                                  of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_UNESCAPED_SLASHES
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
